#!/data/data/com.termux/files/usr/bin/bash
# Termux:Boot launches this on device boot. Bring node_exporter up via
# termux-services (which owns the supervised process).

termux-wake-lock
sv up node_exporter
